version: 2
jobs:
    build:
        docker:
            - image: jonathanschmalhofer/godot-android-template-builder:latest
        steps:
            - setup_remote_docker
            - run:
                name: Prepare workspace for checkout
                command: |
                    mkdir -p ~/work && \
                    cd ~/work
            - run:
                name: Checkout Godot
                command: |
                    cd ~/work && \
                    git clone https://github.com/godotengine/godot.git
            - run:
                name: Build Android Template using Scons and Cradle
                command: |
                    cd ~/work/godot && \
                    scons platform=android target=release android_arch=armv7 && \
                    scons platform=android target=release android_arch=arm64v8 && \
                    scons platform=android target=release android_arch=x86 && \
                    cd platform/android/java && \
                    ./gradlew build
