version: 2
jobs:
    build_android_debug:
        docker:
            - image: jonathanschmalhofer/godot-android-template-builder:latest
        steps:
            - setup_remote_docker
            - run:
                name: Prepare workspace for checkout
                command: |
                    mkdir -p ~/work && \
                    cd ~/work
            - run:
                name: Checkout Godot 3.1.1-stable & Godot-AdMob-Module from Kloder Games
                command: |
                    cd ~/work && \
                    git clone https://github.com/godotengine/godot.git && \
                    git clone https://github.com/kloder-games/godot-admob.git && \
                    mv ~/work/godot-admob/admob ~/work/modules/ && \
                    cd ~/work/godot && \
                    git checkout 3.1.1-stable
            - run:
                name: Build Android Template using Scons and Cradle
                command: |
                    cd ~/work/godot && \
                    scons platform=android target=release_debug android_arch=armv7 && \
                    scons platform=android target=release_debug android_arch=arm64v8 && \
                    cd platform/android/java && \
                    ./gradlew build
            - store_artifacts:
                name: Store results
                path: ~/work/godot/platform/android/java/build/outputs/apk/debug
                destination: target_debug
    build_android_release:
        docker:
            - image: jonathanschmalhofer/godot-android-template-builder:latest
        steps:
            - setup_remote_docker
            - run:
                name: Prepare workspace for checkout
                command: |
                    mkdir -p ~/work && \
                    cd ~/work
            - run:
                name: Checkout Godot 3.1.1-stable & Godot-AdMob-Module from Kloder Games
                command: |
                    cd ~/work && \
                    git clone https://github.com/godotengine/godot.git && \
                    git clone https://github.com/kloder-games/godot-admob.git && \
                    mv ~/work/godot-admob/admob ~/work/modules/ && \
                    cd ~/work/godot && \
                    git checkout 3.1.1-stable
            - run:
                name: Build Android Template using Scons and Cradle
                command: |
                    cd ~/work/godot && \
                    scons platform=android target=release android_arch=armv7 && \
                    scons platform=android target=release android_arch=arm64v8 && \
                    cd platform/android/java && \
                    ./gradlew build
            - store_artifacts:
                name: Store results
                path: ~/work/godot/platform/android/java/build/outputs/apk/release
                destination: target_release
workflows:
  version: 2
  build_debug_and_release:
    jobs:
      - build_android_debug:
          filters:
            branches:
              only: master
      - build_android_release:
          filters:
            branches:
              only: master
